environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    # this is being set in bld.bat of conda-recipe...
    #CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\ci\\appveyor\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"
    
    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27" 
      ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "34"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;"

  - conda config --set always_yes true 
  - conda config --add channels omnia 
  - conda install -q conda-build jinja2 


build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite
  - conda build -q devtools/conda-recipe
